server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    server_tokens off;

    include /etc/nginx/boxed-php-env.conf;

    root /app/public;
    index index.php index.html;

    access_log /proc/self/fd/2 main;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location = /healthz {
        access_log off;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME "";
        fastcgi_pass 127.0.0.1:9000;
    }

    location ~ /\.(?!well-known(?:/|$)) {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
}
