[www]

; Only nginx inside this container should be able to reach FastCGI.
listen = 127.0.0.1:9000
listen.allowed_clients = 127.0.0.1

; We dont need this because nginx already logs each request.
access.log = /dev/null

php_admin_flag[log_errors] = on
catch_workers_output = yes
decorate_workers_output = no

ping.path = /healthz
ping.response = pong
